const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const path = require('path')
const ScriptExtHtmlWebpackPlugin = require('script-ext-html-webpack-plugin')
const CircularDependencyPlugin = require('circular-dependency-plugin')

module.exports = {
    entry: './src/app.component.jsx',
    output: {
        path: path.join(__dirname, 'dist/src'),
        filename: '[name].[hash].bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.jsx$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.scss$/,
                use: [
                    MiniCssExtractPlugin.loader, // creates style nodes from JS strings
                    'css-loader', // translates CSS into CommonJS
                    'sass-loader' // compiles Sass to CSS, using Node Sass by default
                ]
            },
            {
                test: /\.svg$/,
                use: 'file-loader'
            }
        ]
    },
    resolve: {
        extensions: ['.jsx', '.js', '.scss']
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: './public/index.html',
            inject: 'head'
        }),
        new ScriptExtHtmlWebpackPlugin({
            defaultAttribute: 'defer'
        }),
        new MiniCssExtractPlugin({
            filename: 'index.bundle.css'
        })
        // new CircularDependencyPlugin({
        //     // `onStart` is called before the cycle detection starts
        //     onStart({ compilation }) {
        //         console.log('start detecting webpack modules cycles')
        //     },
        //     // `onDetected` is called for each module that is cyclical
        //     onDetected({ module: webpackModuleRecord, paths, compilation }) {
        //         // `paths` will be an Array of the relative module paths that make up the cycle
        //         // `module` will be the module record generated by webpack that caused the cycle
        //         compilation.errors.push(new Error(paths.join(' -> ')))
        //     },
        //     // `onEnd` is called before the cycle detection ends
        //     onEnd({ compilation }) {
        //         console.log('end detecting webpack modules cycles')
        //     }
        // })
    ]
}
